### ISSUE TITLE
对游戏项目是否有效？

### ISSUE THREAD

**Issue by zhaoqingqing** [zfjsyqk/ZFJObsLib#2]
比如U3D开发的游戏，使用C#+Lua或纯C#开发，当然工程中也会有一些第三方的dll，请问作者的工具对游戏这块是否有支持和案例？

**Comment by zfjsyqk** [comment]
可以的



祝你岁月无波澜，敬我余生不悲欢！


------------------ 原始邮件 ------------------
发件人: qingqing.zhao ***@***.***&gt;
发送时间: 2021年7月8日 16:10
收件人: zfjsyqk/ZFJObsLib ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[zfjsyqk/ZFJObsLib] 对游戏项目是否有效？ (#2)





 
比如U3D开发的游戏，使用C#+Lua或纯C#开发，当然工程中也会有一些第三方的dll，请问作者的工具对游戏这块是否有支持和案例？
